name: graph-computation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0.0
  - pandas>=1.5.0
  - networkx>=3.0
  - python-dateutil>=2.8.2
  - pytest>=7.0.0
  - numpy>=1.21.0
  - jupyter>=1.0.0
  - matplotlib>=3.5.0
  - flask>=2.0.0
  - pyodbc>=4.0.35
  - sqlalchemy>=2.0.0
  - pip:
    - black>=22.0.0
    - pylint>=2.14.0
    - flask-cors>=4.0.0
    - pydantic>=2.0.0
    - waitress>=2.1.2  # Windows production server